using Microsoft.EntityFrameworkCore;
using Parley.Domain.Aggregates.ConversationAgg.Entities;
using Parley.Domain.Aggregates.MessageAgg.Entities;
using Parley.Domain.Aggregates.MessageAgg.ValueObjects;
using Parley.Domain.Aggregates.ServerAgg.Entities;
using System.Reflection;

namespace Parley.Infrastructure.Persistence;

/// <summary>
/// Main DbContext for the Parley Discord-clone application.
/// Handles all data persistence for conversations, messages, and servers.
/// Uses EF Core with PostgreSQL and JSONB features for flexible data storage.
/// </summary>
public class ParleyDbContext : DbContext
{
    /// <summary>
    /// DbSet for Conversations (Aggregate Root).
    /// </summary>
    public DbSet<Conversation> Conversations { get; set; }

    /// <summary>
    /// DbSet for ConversationParticipants (Entity).
    /// </summary>
    public DbSet<ConversationParticipant> ConversationParticipants { get; set; }

    /// <summary>
    /// DbSet for Messages (Aggregate Root with Snowflake ID).
    /// </summary>
    public DbSet<Message> Messages { get; set; }

    /// <summary>
    /// DbSet for Servers (Aggregate Root).
    /// </summary>
    public DbSet<Server> Servers { get; set; }

    /// <summary>
    /// DbSet for ServerRoles (Entity).
    /// </summary>
    public DbSet<ServerRole> ServerRoles { get; set; }

    /// <summary>
    /// DbSet for ServerMembers (Entity).
    /// </summary>
    public DbSet<ServerMember> ServerMembers { get; set; }

    /// <summary>
    /// Creates a new instance of ParleyDbContext.
    /// </summary>
    public ParleyDbContext(DbContextOptions<ParleyDbContext> options) : base(options)
    {
    }

    /// <summary>
    /// Configures the database model and entity mappings.
    /// Uses IEntityTypeConfiguration classes from the Configurations folder.
    /// </summary>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Apply all configurations from the current assembly
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }

    /// <summary>
    /// Configures the Conversation aggregate and its entities.
    /// </summary>
    private static void ConfigureConversationAggregate(ModelBuilder modelBuilder)
    {
        // Conversation aggregate root
        modelBuilder.Entity<Conversation>()
            .HasKey(c => c.Id);

        modelBuilder.Entity<Conversation>()
            .Property(c => c.Type)
            .HasConversion<int>();

        modelBuilder.Entity<Conversation>()
            .Property(c => c.ServerId)
            .IsRequired(false);

        modelBuilder.Entity<Conversation>()
            .Property(c => c.Name)
            .HasMaxLength(100)
            .IsRequired(false);

        // Conversation participants
        modelBuilder.Entity<Conversation>()
            .HasMany(c => c.Participants)
            .WithOne()
            .HasForeignKey(cp => cp.ConversationId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<ConversationParticipant>()
            .HasKey(cp => cp.Id);

        modelBuilder.Entity<ConversationParticipant>()
            .Property(cp => cp.ConversationId)
            .IsRequired();

        modelBuilder.Entity<ConversationParticipant>()
            .Property(cp => cp.UserId)
            .IsRequired();

        modelBuilder.Entity<ConversationParticipant>()
            .Property(cp => cp.Role)
            .HasConversion<int>();

        modelBuilder.Entity<ConversationParticipant>()
            .Property(cp => cp.LastReadMessageId)
            .IsRequired(false);

        modelBuilder.Entity<ConversationParticipant>()
            .HasIndex(cp => new { cp.ConversationId, cp.UserId })
            .IsUnique();
    }

    /// <summary>
    /// Configures the Message aggregate and its value objects.
    /// </summary>
    private static void ConfigureMessageAggregate(ModelBuilder modelBuilder)
    {
        // Message aggregate root with long Snowflake ID
        modelBuilder.Entity<Message>()
            .HasKey(m => m.Id);

        // Snowflake ID is never auto-generated (generated by application)
        modelBuilder.Entity<Message>()
            .Property(m => m.Id)
            .ValueGeneratedNever();

        modelBuilder.Entity<Message>()
            .Property(m => m.ConversationId)
            .IsRequired();

        modelBuilder.Entity<Message>()
            .Property(m => m.SenderId)
            .IsRequired();

        modelBuilder.Entity<Message>()
            .Property(m => m.Type)
            .HasConversion<int>();

        modelBuilder.Entity<Message>()
            .Property(m => m.Version)
            .HasDefaultValue(1)
            .IsConcurrencyToken();

        modelBuilder.Entity<Message>()
            .Property(m => m.IsDeleted)
            .HasDefaultValue(false);

        modelBuilder.Entity<Message>()
            .Property(m => m.RepliedToMessageId)
            .IsRequired(false);

        // MessageContent Value Object - stored as JSONB in PostgreSQL
        modelBuilder.Entity<Message>()
            .Property(m => m.Content)
            .HasColumnName("content")
            .HasColumnType("jsonb")
            .IsRequired()
            .HasConversion(
                v => System.Text.Json.JsonSerializer.Serialize(v, System.Text.Json.JsonSerializerOptions.Default),
                v => System.Text.Json.JsonSerializer.Deserialize<MessageContent>(v, System.Text.Json.JsonSerializerOptions.Default)!
            );

        // MentionedUserIds stored as JSONB array
        modelBuilder.Entity<Message>()
            .Property(m => m.MentionedUserIds)
            .HasColumnName("mentioned_user_ids")
            .HasColumnType("jsonb")
            .IsRequired()
            .HasConversion(
                v => System.Text.Json.JsonSerializer.Serialize(v, System.Text.Json.JsonSerializerOptions.Default),
                v => System.Text.Json.JsonSerializer.Deserialize<List<Guid>>(v, System.Text.Json.JsonSerializerOptions.Default) ?? new List<Guid>()
            );

        // Indexes for performance
        modelBuilder.Entity<Message>()
            .HasIndex(m => m.ConversationId);

        modelBuilder.Entity<Message>()
            .HasIndex(m => m.SenderId);

        modelBuilder.Entity<Message>()
            .HasIndex(m => new { m.ConversationId, m.Id });

        modelBuilder.Entity<Message>()
            .HasIndex(m => m.CreatedAt);
    }

    /// <summary>
    /// Configures the Server aggregate and its entities.
    /// </summary>
    private static void ConfigureServerAggregate(ModelBuilder modelBuilder)
    {
        // Server aggregate root
        modelBuilder.Entity<Server>()
            .HasKey(s => s.Id);

        modelBuilder.Entity<Server>()
            .Property(s => s.Name)
            .HasMaxLength(100)
            .IsRequired();

        modelBuilder.Entity<Server>()
            .Property(s => s.Description)
            .HasMaxLength(1000)
            .IsRequired(false);

        modelBuilder.Entity<Server>()
            .Property(s => s.OwnerId)
            .IsRequired();

        modelBuilder.Entity<Server>()
            .Property(s => s.IconUrl)
            .IsRequired(false);

        modelBuilder.Entity<Server>()
            .Property(s => s.IsPublic)
            .HasDefaultValue(false);

        // Server members
        modelBuilder.Entity<Server>()
            .HasMany(s => s.Members)
            .WithOne()
            .HasForeignKey(sm => sm.ServerId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<ServerMember>()
            .HasKey(sm => sm.Id);

        modelBuilder.Entity<ServerMember>()
            .Property(sm => sm.ServerId)
            .IsRequired();

        modelBuilder.Entity<ServerMember>()
            .Property(sm => sm.UserId)
            .IsRequired();

        modelBuilder.Entity<ServerMember>()
            .Property(sm => sm.Nickname)
            .HasMaxLength(32)
            .IsRequired(false);

        modelBuilder.Entity<ServerMember>()
            .Property(sm => sm.RoleIds)
            .HasColumnName("role_ids")
            .HasColumnType("jsonb")
            .HasConversion(
                v => System.Text.Json.JsonSerializer.Serialize(v, System.Text.Json.JsonSerializerOptions.Default),
                v => System.Text.Json.JsonSerializer.Deserialize<List<Guid>>(v, System.Text.Json.JsonSerializerOptions.Default) ?? new List<Guid>()
            );

        modelBuilder.Entity<ServerMember>()
            .HasIndex(sm => new { sm.ServerId, sm.UserId })
            .IsUnique();

        // Server roles
        modelBuilder.Entity<Server>()
            .HasMany(s => s.Roles)
            .WithOne()
            .HasForeignKey(sr => sr.ServerId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<ServerRole>()
            .HasKey(sr => sr.Id);

        modelBuilder.Entity<ServerRole>()
            .Property(sr => sr.ServerId)
            .IsRequired();

        modelBuilder.Entity<ServerRole>()
            .Property(sr => sr.Name)
            .HasMaxLength(100)
            .IsRequired();

        modelBuilder.Entity<ServerRole>()
            .Property(sr => sr.Permissions)
            .HasConversion<ulong>();

        modelBuilder.Entity<ServerRole>()
            .Property(sr => sr.Color)
            .HasMaxLength(7)
            .IsRequired(false);

        modelBuilder.Entity<ServerRole>()
            .Property(sr => sr.Position)
            .HasDefaultValue(0);

        modelBuilder.Entity<ServerRole>()
            .HasIndex(sr => new { sr.ServerId, sr.Name })
            .IsUnique();
    }

    /// <summary>
    /// Overrides SaveChanges to update timestamps.
    /// </summary>
    public override int SaveChanges()
    {
        UpdateTimestamps();
        return base.SaveChanges();
    }

    /// <summary>
    /// Overrides SaveChangesAsync to update timestamps.
    /// </summary>
    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        UpdateTimestamps();
        return base.SaveChangesAsync(cancellationToken);
    }

    /// <summary>
    /// Updates CreatedAt and UpdatedAt timestamps for tracked entities.
    /// </summary>
    private void UpdateTimestamps()
    {
        var entries = ChangeTracker.Entries()
            .Where(e => e.Entity.GetType().GetProperty("CreatedAt") != null);

        foreach (var entry in entries)
        {
            if (entry.State == EntityState.Added)
            {
                entry.Property("CreatedAt").CurrentValue = DateTime.UtcNow;
            }

            if (entry.State == EntityState.Modified)
            {
                entry.Property("UpdatedAt").CurrentValue = DateTime.UtcNow;
            }
        }
    }
}

