using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Parley.Domain.Aggregates.MessageAgg.Entities;
using Parley.Domain.Aggregates.MessageAgg.Enums;
using Parley.Domain.Aggregates.MessageAgg.ValueObjects;
using System.Text.Json;

namespace Parley.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core configuration for Message aggregate root.
/// CRITICAL: Message uses Snowflake ID (long) for high-scale chronological sorting.
/// MessageContent is stored as JSONB in PostgreSQL for flexibility.
/// </summary>
public class MessageConfiguration : IEntityTypeConfiguration<Message>
{
    public void Configure(EntityTypeBuilder<Message> builder)
    {
        // Table name
        builder.ToTable("messages");

        // Primary Key - Snowflake ID (long)
        builder.HasKey(m => m.Id);

        // CRITICAL: Snowflake ID is NEVER auto-generated by the database
        builder.Property(m => m.Id)
            .HasColumnName("id")
            .ValueGeneratedNever()
            .IsRequired();

        // Properties
        builder.Property(m => m.ConversationId)
            .HasColumnName("conversation_id")
            .IsRequired();

        builder.Property(m => m.SenderId)
            .HasColumnName("sender_id")
            .IsRequired();

        builder.Property(m => m.Type)
            .HasColumnName("type")
            .HasConversion<int>()
            .IsRequired();

        builder.Property(m => m.RepliedToMessageId)
            .HasColumnName("replied_to_message_id")
            .IsRequired(false);

        builder.Property(m => m.IsDeleted)
            .HasColumnName("is_deleted")
            .HasDefaultValue(false)
            .IsRequired();

        builder.Property(m => m.CreatedAt)
            .HasColumnName("created_at")
            .IsRequired();

        builder.Property(m => m.UpdatedAt)
            .HasColumnName("updated_at")
            .IsRequired(false);

        // Optimistic Concurrency Control
        builder.Property(m => m.Version)
            .HasColumnName("version")
            .HasDefaultValue(1)
            .IsConcurrencyToken()
            .IsRequired();

        // JSONB Configuration for MessageContent (Value Object)
        builder.Property(m => m.Content)
            .HasColumnName("content")
            .HasColumnType("jsonb")
            .IsRequired()
            .HasConversion(
                v => JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                v => JsonSerializer.Deserialize<MessageContent>(v, (JsonSerializerOptions?)null)!
            );

        // JSONB Configuration for MentionedUserIds (List<Guid>)
        builder.Property(m => m.MentionedUserIds)
            .HasColumnName("mentioned_user_ids")
            .HasColumnType("jsonb")
            .IsRequired()
            .HasConversion(
                v => JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                v => JsonSerializer.Deserialize<List<Guid>>(v, (JsonSerializerOptions?)null) ?? new List<Guid>()
            );

        // Indexes for Query Performance
        
        // Index on ConversationId (most common query pattern)
        builder.HasIndex(m => m.ConversationId)
            .HasDatabaseName("ix_messages_conversation_id");

        // Composite index for pagination queries (ConversationId + Id for cursor-based pagination)
        builder.HasIndex(m => new { m.ConversationId, m.Id })
            .HasDatabaseName("ix_messages_conversation_id_id");

        // Index on SenderId (for user message history)
        builder.HasIndex(m => m.SenderId)
            .HasDatabaseName("ix_messages_sender_id");

        // Index on CreatedAt (for time-based queries)
        builder.HasIndex(m => m.CreatedAt)
            .HasDatabaseName("ix_messages_created_at");

        // Index on RepliedToMessageId (for finding replies)
        builder.HasIndex(m => m.RepliedToMessageId)
            .HasDatabaseName("ix_messages_replied_to_message_id");

        // GIN Index for JSONB mentioned_user_ids (PostgreSQL-specific, for contains queries)
        // This will be added via raw SQL in migrations if needed
        // builder.HasIndex(m => m.MentionedUserIds)
        //     .HasMethod("gin"); // Requires Npgsql-specific extension
    }
}

